# LightVoting Config

variables:
  runs: '100'
  setting1: 'RANDOM_BASIC'
  rule: 'MINISUM_APPROVAL'
  agnum: '41'
  altnum: '10'
  comsize: '5'
  capacity: '1'
  dissthr:  '-1'
  jointhr: '-1'
  preferences: 'FSquare'


