# LightVoting Default Config

variables:
  grouping: COORDINATED
  protocol: BASIC
  altnum: '6'

# TODO set other parameters here -> capacity, diss threshold, join threshold, (number of) alternatives
