# LightVoting Config

variables:
  runs: '1'
  setting1: 'COORDINATED_ITERATIVE'
  rule: 'MINISUM_APPROVAL'
  agnum: '11'
  altnum: '10'
  comsize: '5'
  capacity: '5'
  dissthr:  '3.9'
  jointhr: '-1'
  preferences: 'uniform'


