# LightVoting Default Config

variables:
  runs: '100'
  config: 'RANDOM_BASIC'
  agnum: '25'
  altnum: '10'
  comsize: '5'
  capacity: '5'
  dissthr:  '1.4'
  jointhr: '3'
  preferences: 'FScluster'
