# LightVoting Config

variables:
  runs: '1'
  setting1: 'RANDOM_BASIC'
  rule: 'MINISUM_APPROVAL'
  agnum: '11'
  altnum: '10'
  comsize: '5'
  capacity: '5'
  dissthr:  '3'
  jointhr: '3'
  preferences: 'FSquare'


