# LightVoting Default Config

variables:
  runs: '100'
  setting: 'RANDOM_BASIC'
  agnum: '10'
  altnum: '10'
  comsize: '5'
  capacity: '3'
#  dissthr:  '1.4'
#  jointhr: '3'
  preferences: 'uniform'
