# LightVoting Config

variables:
  runs: '1'
  setting1: 'RANDOM_BASIC'
  rule: 'MINIMAX_APPROVAL'
  ndiss: 'true'
  agnum: '41'
  altnum: '20'
  comsize: '5'
  capacity: '20'
  dissthr:  '-1'
  jointhr: '-1'
  preferences: 'FSquare'



