# LightVoting Default Config

variables:
  runs: '100'
  config1: 'RANDOM_BASIC'
  config2: 'RANDOM_ITERATIVE'
  altnum: '10'
  comsize: '3'
  dissthr:  '1.4'
  capacity: '3'
  jointhr: '3'
  preferences: 'sigmoid'
