# LightVoting Config

variables:
  runs: '100'
  setting1: 'COORDINATED_BASIC'
  rule: 'MINISUM_RANKSUM'
  ndiss: 'true'
  agnum: '41'
  altnum: '20'
  comsize: '5'
  capacity: '20'
  dissthr:  '-1'
  jointhr: '18'
  preferences: 'FSquare'



