# LightVoting Default Config

variables:
  runs: '1'
  grouping: 'RANDOM'
  protocol: 'BASIC'
  altnum: '6'

# TODO set other parameters here -> capacity, diss threshold, join threshold, (number of) alternatives
