# LightVoting Config

variables:
  runs: '1'
  setting1: 'COORDINATED_BASIC'
  rule: 'MINISUM_APPROVAL'
  agnum: '41'
  altnum: '10'
  comsize: '5'
  capacity: '20'
  dissthr:  '-1'
  jointhr: '100'
  preferences: 'FSquare'


